import Config

# Configure your database
config :insider_trading, InsiderTrading.Repo,
  username: System.get_env("DB_USER_NAME", "postgres") || "postgres",
  password: System.get_env("DB_PASSWORD", "postgres") || "postgres",
  hostname: System.get_env("DB_HOST_NAME", "localhost") || "localhost",
  database: System.get_env("DB_NAME", "insider_trading_dev") || "insider_trading_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :insider_trading, InsiderTradingWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "h2F5s8hd4WTrej21QpznThZVR4vLFwnV+/Z/qZJoLWzwwD0BZP+2px6SUMPJf0rb",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :insider_trading, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# EDGAR APIs Config
config :insider_trading,
  edgar_url_template:
    System.get_env(
      "EDGAR_URL_TEMPLATE",
      "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=%k&type=4&company=&dateb=%b&datea=%a&owner=include&start=%s&count=%c&output=atom"
    )

config :insider_trading,
  market_cap_url_template:
    System.get_env(
      "MARKET_CAP_URL_TEMPLATE",
      "https://query2.finance.yahoo.com/v10/finance/quoteSummary/?symbol=%t&modules=summaryDetail"
    )
